### ISSUE TITLE
Remove requires of jquery & selectize for inclusion in the project.

### ISSUE THREAD

**Issue by NicholasAzar** [NicholasAzar/ng2-selectize#16]

**Comment by astroanu** [comment]
Is this a fix to not use jquery with the plugin.?

I'm using latest version and it says $ is undefined. Including jquery in an angular project does not seem okay for me :(

**Comment by NicholasAzar** [comment]
Hi @astroanu -- no, it was just for replacing the require('...') 's with imports.

If you have a repo with your issue up anywhere link it and i'll see if I can help

**Comment by astroanu** [comment]
I see, my issue is not related to this issue then. Is there a way to use ng-selectize in angular project without including jquery ?

**Comment by NicholasAzar** [comment]
@astroanu unfortunately no, the ng-selectize module is just a wrapper over the selectize jquery plugin.
