### ISSUE TITLE
lodash dependency not declared in package

### ISSUE THREAD

**Issue by genuinefafa** [NicholasAzar/ng2-selectize#22]
Do I need to manually install lodash library? I'm not currently using in the project and was unaware of the dependency.

```
ERROR in ../node_modules/ng2-selectize/src/ng2-selectize/ng2-selectize.component.ts (5,23): Cannot find module 'lodash-es/cloneDeep'.)
../node_modules/ng2-selectize/src/ng2-selectize/ng2-selectize.component.ts (6,21): Cannot find module 'lodash-es/isEqual'.)
../node_modules/ng2-selectize/src/ng2-selectize/ng2-selectize.component.ts (7,18): Cannot find module 'lodash-es/find'.)
../node_modules/ng2-selectize/src/ng2-selectize/ng2-selectize.component.ts (8,28): Cannot find module 'lodash-es/differenceWith'.)
```

**Comment by NicholasAzar** [comment]
Hi @genuinefafa, thanks for letting me know about this.. I was careless in my last commit.

Will be fixed this weekend.

**Comment by NicholasAzar** [comment]
Hey, try it out with 1.0.1 and let me know if you still have this issue. Please note the updated installation instructions in the readme.md (some paths have changed).

**Comment by genuinefafa** [comment]
all set dude! it does work, now is up to me deal with it ;) thanks!

ps: nicely done using latest updates of angular-cli too :clap:
