### ISSUE TITLE
 Unexpected value 'Ng2SelectizeModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [NicholasAzar/ng2-selectize#3]
Hi, 

So I tried to follow your instructions, having this import in my app.module.ts file

`import { Ng2SelectizeModule } from 'ng2-selectize';

@NgModule({
	imports: [
		BrowserModule
		, FormsModule
		, HttpModule
		, Ng2SelectizeModule 
	],
	declarations: [
		AppComponent
		, TabPanelComponent
		, TabComponent
		, ObservablesComponent
	],
	bootstrap: [AppComponent]
})

export class AppModule { }`

However, upon running the app I came across the error above. Could you please shed some lights on how to resolve this issue?

I'm using webpack if that helps.

Thanks.
Tam

**Comment by NicholasAzar** [comment]
Hey Tam, which version of ng2-selectize are you using? There was a change in one of the more recent releases to change the module import to non-default (requires curly brackets) where it didnt before.

**Comment by judezhu** [comment]
I came across the same problem too, using v0.0.18.

**Comment by NicholasAzar** [comment]
That's really strange as i just tried it empty test project and it works as is for me.. my only guess could be how im exporting from index.ts... could you guys try to modify the index.ts from node_modules/ng2-selectize/index.ts for it to be:

import {Ng2SelectizeModule} from './src/....';
export {Ng2SelectizeModule};

And see if that fixes it?

**Comment by minhtam-nguyennhat** [comment]
Hi Nick, 

Thanks the above seems to fix the problem. All is good now :) Thanks heaps 

Tam.

**Comment by NicholasAzar** [comment]
Hi @JulioWar! Thank you for that link. I'll definitely take a look into that article and work on the package resolutions.

And I would absolutely appreciate any help you would be able to provide.. If there's any issues you find or features you're looking for don't hesitate to open them as issues and assign them as you see fit. Or if you just want to open a pr directly, i'll certainly merge as soon as I can.

Thanks again!
